Friction Energy Output in H3D file
OpenRadioss/OpenRadioss pull request #1106
Opened 2023-02-10 09:43 UTC by MahaHachani

#### Checklist

- [ ] The title of the PR is reviewed
- [ ] There is no text before the checklist section
- [ ] The following two sections are filled (or deleted)
- [ ] This PR has been previewed 

Description of the feature or the bug

New development for outputting friction energie in H3d file
/H3D/NODA/CSE_FRICG
/H3D/NODA/CE_FRIC/INTER=ID or ALL
Description of the changes

New development for outputting friction energie in H3d file:
The energy is stored in variables EFRIC and EFRICG
Communication spmd for remote nodes
Before outputting the energy is divided by the surface

2023-02-10 12:53 UTC, sebastienVilleneuve requested changes
@MahaHachani 

some other issues to correct

2023-02-10 12:53 UTC, sebastienVilleneuve commented on engine/source/mpi/interfaces/spmd_exch_efric.F
> +      TYPE(INTBUF_STRUCT_),INTENT(IN) ::  INTBUF_TAB(*)
@MahaHachani 

you need to put size of the array

2023-02-10 12:53 UTC, sebastienVilleneuve commented on engine/source/mpi/interfaces/spmd_exch_sorting_efric.F
> +      TYPE(INTBUF_STRUCT_),INTENT(IN) ::  INTBUF_TAB(*)
size of the array must be specified

2023-02-10 12:53 UTC, sebastienVilleneuve commented on engine/source/output/h3d/spmd/spmd_h3d_sum_r_nodal_value.F
> +      INTEGER  , INTENT(IN) :: LEN,LENP0, NODGLOB(*)
size of the array must be specified

2023-02-10 13:56 UTC, MahaHachani commented on engine/source/output/h3d/spmd/spmd_h3d_sum_r_nodal_value.F
> +      INTEGER  , INTENT(IN) :: LEN,LENP0, NODGLOB(*)
Done Sebastien
Thanks

2023-02-13 15:33 UTC, sebastienVilleneuve requested changes

2023-02-13 15:33 UTC, sebastienVilleneuve commented on engine/source/input/lectur.F
> +            EFRIC_STAMP(1:NINEFRICG,1:NUMNODG) = ZERO
@MahaHachani 

please use MY_ALLOCATE routines

2023-02-13 17:53 UTC, MahaHachani commented on engine/source/output/h3d/spmd/spmd_h3d_sum_r_nodal_value.F
> +      INTEGER  , INTENT(IN) :: LEN,LENP0, NODGLOB(*)
Done

2023-02-13 18:51 UTC, sebastienVilleneuve approved these changes

2023-02-13 18:51 UTC, merged