Sensor data structure : clean all sensor data from common include files
OpenRadioss/OpenRadioss pull request #1433
Opened 2023-05-03 15:09 UTC by MaciekWronski

Sensor data structure :  reorganise top level sensor module, clean sensor data from common files

#### Description of the changes

added top level sensor type containing NSENSOR variable and allocatable sensor data structure
include sensor lists for engine options /*/LSENSOR which are now deleted from common include files

2023-05-03 16:57 UTC, laurent-altr requested changes
Hello @MaciekWronski, 

Could you please review the commit message: 
https://openpbs.atlassian.net/wiki/spaces/DG/pages/6193155/How+To+Write+a+Good+Git+Commit+Message

2023-05-04 13:30 UTC, sebastienVilleneuve requested changes
some INTENT statement are missing
SENSORS is not passed by arguments in several routines

2023-05-04 13:30 UTC, sebastienVilleneuve commented on engine/source/mpi/interfaces/spmd_ifront.F
> +     .        IRLEN20E,ISLEN20E, NSENSOR,
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on engine/source/output/h3d/h3d_build_fortran/h3d_read.F
> +      TYPE (SENSORS_)     :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on engine/source/output/report/report.F
> +       IF(SENSORS%NSENSOR /= 0)THEN
SENSORS not passed by argument

2023-05-04 13:30 UTC, sebastienVilleneuve commented on engine/source/output/restart/read_sensors.F
> +      TYPE (SENSORS_) ,TARGET :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on engine/source/output/sortie_main.F
> +      TYPE (SENSORS_) :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/user_interface/uaccess.F
> +      ITYP = SENSORS%SENSOR_TAB(NSENS)%TYPE
SENSOR not passed by argument

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/tools/sensor/sort_logical_sensors.F
> +      INTEGER NSENSOR
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/tools/sensor/sensor_tab_init.F
> +      TYPE (SENSORS_) :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/tools/sensor/inisen.F
> +      INTEGER NSENSOR
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/tools/sensor/hm_read_sensors.F
> +      TYPE (SENSORS_)  ,TARGET    :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/tools/seatbelts/create_seatbelt.F
> +      TYPE (SENSORS_) :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/system/fsdcod.F
> +      TYPE (SENSORS_)  :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/starter/lectur.F
> +     8           NLOC_DMG ,DETONATORS,SENSORS%NSENSOR)
SENSOR not passed by argument ( no global variable allowed)

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/restart/ddsplit/w_front.F
> +     .          NBDDEDGT,NBDDEDG_MAX,NSENSOR,
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on engine/source/tools/sensor/sensor_dist_surf0.F
> +      TYPE (SENSOR_STR_), DIMENSION(NSENSOR) :: SENSOR_TAB
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on engine/source/user_interface/usensor.F
> +      DO J=1,SENSORS%NSENSOR
SENSOR not passed by arguments

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/airbag/hm_read_monvol_type11.F
> +      TYPE (SENSORS_)  :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/airbag/hm_read_monvol_type5.F
> +      TYPE (SENSORS_)  :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/airbag/hm_read_monvol_type6.F
> +      TYPE (SENSORS_)  :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/airbag/hm_read_monvol_type7.F
> +      TYPE (SENSORS_)  :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/airbag/hm_read_monvol_type8.F
> +      TYPE (SENSORS_)  :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/airbag/hm_read_monvol_type9.F
> +      TYPE (SENSORS_)  :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/airbag/init_monvol.F
> +      TYPE (SENSORS_)  :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/boundary_conditions/ebcs/iniebcs.F
> +      TYPE (SENSORS_)  :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/interfaces/int07/hm_read_inter_type07.F
> +      TYPE (SENSORS_)  :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/interfaces/int11/hm_read_inter_type11.F
> +      TYPE (SENSORS_)  :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/interfaces/int21/hm_read_inter_type21.F
> +      TYPE (SENSORS_)  :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/interfaces/int24/hm_read_inter_type24.F
> +      TYPE (SENSORS_)  :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/interfaces/int25/hm_read_inter_type25.F
> +      TYPE (SENSORS_)  :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/interfaces/reader/hm_read_inter_struct.F
> +      TYPE (SENSORS_)  :: SENSORS
INTENT statement is missing

2023-05-04 13:30 UTC, sebastienVilleneuve commented on starter/source/loads/general/load_centri/hm_read_load_centri.F
> +      TYPE (SENSORS_)  :: SENSORS
INTENT statement is missing

2023-05-04 16:15 UTC, closed without merging