add hourglass control in penta6 thickshell
OpenRadioss/OpenRadioss pull request #1453
Opened 2023-05-09 15:18 UTC by qiangRadioss

#### Description of the feature or the bug

some tests shown the hourglass results with penta6 thickshell elements

#### Description of the changes

adding hourglass controls (in thickness direction) in penta6 element

2023-05-12 07:18 UTC, sebastienVilleneuve requested changes
Hi @qiangRadioss 

can you add teh INTENT statements that are missing please .

Thanks,
Sébastien

2023-05-12 07:18 UTC, sebastienVilleneuve commented on engine/source/elements/thickshell/solide6c/s6chourg3.F
> +      INTEGER NEL
Hi @qiangRadioss 

INTENT statement are missing

2023-05-12 10:52 UTC, qiangRadioss commented on engine/source/elements/thickshell/solide6c/s6chourg3.F
> +      INTEGER NEL
done, thanks

2023-05-15 06:07 UTC, sebastienVilleneuve approved these changes

2023-05-15 06:53 UTC, merged