adding product_name & correct the listing file and improve the error 373 message
OpenRadioss/OpenRadioss pull request #1563
Opened 2023-06-09 15:01 UTC by SaidMamouri

#### Description of the feature or the bug

Error message 373 not clear.
Error in the listing file

#### Description of the changes

Improve the error message 373
correct the listing file
adding product name the /PROP/PLY and /PLY

2023-06-12 06:05 UTC, laurent-altr submitted a review, later dismissed

2023-06-12 06:09 UTC, sebastienVilleneuve requested changes

2023-06-12 06:09 UTC, sebastienVilleneuve commented on hm_cfg_files/config/CFG/radioss2023/PLY/ply.cfg
> +    //@Ranjith
@SaidMamouri 

can you remove this comment please ?

2023-06-15 05:13 UTC, sebastienVilleneuve approved these changes

2023-06-15 06:08 UTC, merged