add /LOAD/PCYL compatible with /H3D/ELEM/PEXT
OpenRadioss/OpenRadioss pull request #1584
Opened 2023-06-14 15:19 UTC by qiangRadioss

#### Description of the feature or the bug

#### Description of the changes

make compatible output /H3D/ELEM/PEXT for new /LOAD/PCYL

2023-06-14 15:40 UTC, sebastienVilleneuve requested changes

2023-06-14 15:40 UTC, sebastienVilleneuve commented on engine/source/input/lectur.F
> +      TYPE (LOADS_)                          :: LOADS
Hi @qiangRadioss 

INTENT statement is missing here

2023-06-14 15:40 UTC, sebastienVilleneuve commented on engine/source/output/h3d/h3d_results/genh3d.F
> +      INTEGER ILOADP(SIZLOADP,*),IBCL(NIBCLD,*),IFRAME(LISKN,*)
INTENT  statement is missing

2023-06-14 15:40 UTC, sebastienVilleneuve commented on engine/source/output/h3d/h3d_results/genh3d.F
> +      INTEGER ILOADP(SIZLOADP,*),IBCL(NIBCLD,*),IFRAME(LISKN,*)
"*" is not allowed in dimensions

2023-06-14 15:40 UTC, sebastienVilleneuve commented on engine/source/output/h3d/h3d_results/h3d_skin_ixskin.F
> +		   NP = NP + 1
indentation to correct

2023-06-14 15:40 UTC, sebastienVilleneuve commented on engine/source/output/h3d/h3d_results/h3d_skin_scalar.F
> +      INTEGER ,       DIMENSION(LISKN,*)  ,INTENT(IN) :: IFRAME
"*" not allowed

2023-06-14 15:40 UTC, sebastienVilleneuve commented on engine/source/output/h3d/h3d_results/h3d_skin_scalar.F
> +      INTEGER ,       DIMENSION(LISKN,*)  ,INTENT(IN) :: IFRAME
"*" not allowed

2023-06-14 15:40 UTC, sebastienVilleneuve commented on engine/source/output/h3d/h3d_results/h3d_skin_scalar.F
> +		     IF (H3D_PART(NODAL_IPART(N1))==1) IS_WRITTEN_SKIN(NSKIN)=1
some tabulations to remove

2023-06-14 15:40 UTC, sebastienVilleneuve commented on engine/source/output/h3d/h3d_results/h3d_skin_scalar.F
> +		   IF (N1==0.OR.N2==0.OR.N3==0) CYCLE
tabulations to remove

2023-06-14 15:40 UTC, sebastienVilleneuve commented on engine/source/output/h3d/h3d_results/h3d_skin_vector.F
> +      INTEGER ,       DIMENSION(LISKN,*)  ,INTENT(IN) :: IFRAME
"*" not allowed

2023-06-14 15:40 UTC, sebastienVilleneuve commented on engine/source/output/h3d/h3d_results/h3d_skin_vector.F
> +		     IF (H3D_PART(NODAL_IPART(N1))==1) IS_WRITTEN_SKIN(NSKIN)=1
tabulation to remove

2023-06-14 16:18 UTC, qiangRadioss commented
done after the comments.
thanks.

2023-06-19 07:22 UTC, sebastienVilleneuve approved these changes

2023-06-19 14:21 UTC, merged