Add element deletion and revision of /MAT/LAW79
OpenRadioss/OpenRadioss pull request #1671
Opened 2023-07-04 15:11 UTC by vdavaze

#### Description of the feature or the bug

Add element deletion in /MAT/LAW79 + clean code (intent attribute, arguments, comments ...) and review constitutive equations. 

#### Description of the changes

Element deletion is now available and constitutive equations have been verified with comparisons of numerical results.

2023-07-05 11:41 UTC, sebastienVilleneuve approved these changes

2023-07-05 13:46 UTC, sebastienVilleneuve requested changes
@vdavaze 

It is no more allowed to add .inc in the code.
Can you add the used variables as arguments ?

Thanks,
Sébastien

2023-07-06 12:29 UTC, vdavaze commented
Hi @sebastienVilleneuve 

Changes requested have been made. 

Thanks a lot :) !

2023-07-07 08:20 UTC, sebastienVilleneuve approved these changes

2023-07-07 08:20 UTC, merged