SPH order 1 - SPMD compatibility
OpenRadioss/OpenRadioss pull request #2079
Opened 2023-11-14 15:55 UTC by bertrand-altair

New way tom compute correction order 1 for SPH + SPMD compatibility (old cold is kept in comment)

2023-11-15 08:08 UTC, sebastienVilleneuve commented on engine/source/elements/sph/spcompl.F
> +     .        SPH_IORD1
INTENT statement is missing here

2023-11-15 08:21 UTC, sebastienVilleneuve commented on engine/source/elements/sph/spcompl.F
> +        WACOMP( 2,N)=ONE/SIGN(MAX(EM20,ABS(WCOMPXI)),WCOMPXI)
' ' char here : WACOMP( 2,N)

2023-11-15 08:22 UTC, sebastienVilleneuve commented on engine/source/mpi/elements/spmd_sph.F
> +       INTEGER SPH_IORD1
INTENT statement is missing

2023-11-15 08:23 UTC, sebastienVilleneuve commented on engine/source/mpi/elements/spmd_sph.F
> +       INTEGER SPH_IORD1
INTENT statement is missing

2023-11-15 08:23 UTC, sebastienVilleneuve commented on engine/source/elements/sph/sphprep.F
> +     .    IRUNN_BIS,SPH_IORD1
INTENT statement missing

2023-11-15 08:24 UTC, sebastienVilleneuve commented on engine/source/elements/forintp.F
> +     .   SPH_IORD1
INTENT statement missing

2023-11-17 11:40 UTC, bertrand-altair commented on engine/source/elements/sph/spcompl.F
> +     .        SPH_IORD1
done

2023-11-17 11:41 UTC, bertrand-altair commented on engine/source/elements/sph/spcompl.F
> +        WACOMP( 2,N)=ONE/SIGN(MAX(EM20,ABS(WCOMPXI)),WCOMPXI)
done

2023-11-17 11:41 UTC, bertrand-altair commented on engine/source/mpi/elements/spmd_sph.F
> +       INTEGER SPH_IORD1
done

2023-11-17 11:41 UTC, bertrand-altair commented on engine/source/elements/sph/sphprep.F
> +     .    IRUNN_BIS,SPH_IORD1
done

2023-11-17 11:41 UTC, bertrand-altair commented on engine/source/elements/forintp.F
> +     .   SPH_IORD1
done

2023-11-20 07:51 UTC, sebastienVilleneuve commented
Hi @bertrand-altair 

In this PR there are 2 commit , could you squash them ?

Thanks,
Sébastien

2023-11-20 15:57 UTC, sebastienVilleneuve requested changes
Hi @bertrand-altair 

I can see 2 commits in this PR , can you squash them ?

Thanks,
Sébastien

2023-11-21 11:44 UTC, sebastienVilleneuve approved these changes

2023-11-21 12:58 UTC, merged