force.F90 : issue in variable length
OpenRadioss/OpenRadioss pull request #2579
Opened 2024-05-03 13:35 UTC by OlivierWienholtz

force.F90 : issue in variable length
After force.F translation in force.F90 : skew length mismatch.

#### Description of the feature or the bug

#### Description of the changes

2024-05-06 07:40 UTC, laurent-altr requested changes

2024-05-06 07:40 UTC, laurent-altr commented on engine/source/loads/general/force_imp.F
> +      print*,'SMPC=',SNPC,NFUNCT
Debug print here

2024-05-09 15:20 UTC, OlivierWienholtz commented on engine/source/loads/general/force_imp.F
> +      print*,'SMPC=',SNPC,NFUNCT
Done
Thank You

2024-05-13 07:21 UTC, laurent-altr approved these changes

2024-05-13 09:34 UTC, merged