Correction of strain rate effect in law83
OpenRadioss/OpenRadioss pull request #2685
Opened 2024-05-21 15:30 UTC by MaciekWronski

#### Description of the feature or the bug

strain rate was not calculated except when plastic strain rate was chosen (ISRATE=1)

#### Description of the changes

corrected strain rate calculation including filtering by default

corrected plasticity projection algorithm

2024-05-22 12:12 UTC, sebastienVilleneuve requested changes
@MaciekWronski , one argument declred in 'dummy argument' section , but is not dummy

coudl you correct?

Thanks,
Sébastien

2024-05-22 12:12 UTC, sebastienVilleneuve commented on engine/source/materials/mat/mat083/sigeps83.F
> +      INTEGER NEL,NUPARAM,NUVAR,MAXFUNC,JSMS,VP
VP is not a dummy argument

2024-05-23 07:08 UTC, MaciekWronski commented on engine/source/materials/mat/mat083/sigeps83.F
> +      INTEGER NEL,NUPARAM,NUVAR,MAXFUNC,JSMS,VP
thanks, it's done

2024-05-23 15:58 UTC, laurent-altr approved these changes

2024-05-24 15:06 UTC, sebastienVilleneuve approved these changes

2024-05-27 05:15 UTC, merged