fix P/ON issue of shell offset support contact
OpenRadioss/OpenRadioss pull request #3187
Opened 2024-12-05 12:32 UTC by qiangRadioss

#### Description of the feature or the bug

option shell offset support contact might not be P/ON (np>1) for some cases.
#### Description of the changes

fix P/ON issue of shell offset support contact

2024-12-05 13:57 UTC, laurent-altr requested changes
Please note that  `X_C => X` is illegal in this case.
I know it that this illegal usage has not been introduced by this PR, but it is starting to be blocking now.

2024-12-06 14:04 UTC, qiangRadioss commented
pointer removed as required.

thanks.
Qiang.

2024-12-09 08:03 UTC, laurent-altr approved these changes

2024-12-09 10:57 UTC, laurent-altr approved these changes

2024-12-09 10:57 UTC, merged