/INIBRI/EREF+ITETRA4=1
OpenRadioss/OpenRadioss pull request #460
Opened 2022-09-14 15:06 UTC by qiangRadioss

#### Description of the feature or the bug
/INIBRI/EREF +Itetra4=1 hadn't the consisting result w.r.t. runs using restart

#### Description of the changes
inconsistent result is due missed historic rotation values (used by Itetra4=1) with /INIBRI/EREF, these nodal rotations have been added now in /INIBRI/EREF, then the inconsistent issue has been fixed

2022-09-14 15:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenRadioss/OpenRadioss?pullRequest=460) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenRadioss/OpenRadioss?pullRequest=460) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenRadioss/OpenRadioss?pullRequest=460) it.</sub>

2022-09-14 15:15 UTC, qiangRadioss commented
some arrays are still declared by (*), eg. DR(3,*), the reason is that DR is n't always be allocated (under some conditions); Another example is IXS(NIXS,*), because the calling of this subroutine has been done with a offset :IXS(1,NF1).

2022-09-15 08:12 UTC, sebastienVilleneuve requested changes
Hi @qiangRadioss 
Even with array with size 0 , you need to explicit the argument size
( DR seems always allocated, we cannot pass a not allocated arrray in argument of a subroutine)
Concerning , IXS , you need also to explicit the dim , taking the offset into account.

Thanks ,

2022-09-15 11:31 UTC, sebastienVilleneuve submitted a review, later dismissed

2022-09-15 11:34 UTC, sebastienVilleneuve approved these changes

2022-09-15 12:20 UTC, merged