Law80 solid exe intel stops with error
OpenRadioss/OpenRadioss pull request #480
Opened 2022-09-16 14:47 UTC by pmondalek

Correct the equation for the transformation of bainite during cooling. Must have considered the equilibrium fraction

change to take into account the equilibrium fraction for bainite as for pearlite.

2022-09-16 14:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenRadioss/OpenRadioss?pullRequest=480) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenRadioss/OpenRadioss?pullRequest=480) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenRadioss/OpenRadioss?pullRequest=480) it.</sub>

2022-09-16 15:14 UTC, laurent-altr approved these changes

2022-09-19 05:11 UTC, sebastienVilleneuve requested changes
Hi @pmondalek , we can not merge your PR since there are 2 commits .
Can you correct this please ?

Thanks,
Sébastien

2022-09-19 07:27 UTC, sebastienVilleneuve approved these changes

2022-09-19 08:01 UTC, merged