Max_contact_pressure_output
OpenRadioss/OpenRadioss pull request #841
Opened 2022-11-23 16:09 UTC by MahaHachani

#### Description of the feature or the bug

Compute and output the maximum of contact pressure in H3D file 

#### Description of the changes

Compute and output the maximum of contact pressure in H3D file  (FN_MAX and FT_MAX)

2022-11-25 06:09 UTC, sebastienVilleneuve requested changes
Hi @MahaHachani 
It is not allowed anymore to work with COMMON , please put SFCONT_MAX & SPCONT_MAX in a module instead (cf Guidelines and coding style)

Thanks,
Sébastien

2022-11-29 14:46 UTC, MahaHachani commented
Hi Thank you for reviewing
I corrected that 
thank you

2022-11-29 15:01 UTC, sebastienVilleneuve approved these changes

2022-11-29 15:01 UTC, sebastienVilleneuve commented
@MahaHachani 
Thanks for the correction

Sébastien

2022-11-30 06:26 UTC, merged